version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
